git:
  pagers:
    - colorArg: always
      pager: delta --syntax-theme base16-256
  showIcons: true
gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
