local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("cmp-start-build", {
    t { "services:", "  " },
    i(1, "app"),
    t { ":", "    build: .", "    ports:", "      - " },
    i(2, "8080:8080"),
    t { "", "    depends_on:", "      - " },
    i(3, "db"),
    t { "", "    env_file:", "      - .env", "    environment:", "      - " },
    i(4, "ENV=dev"),
    t { "", "    restart: unless-stopped", "    networks:", "      - " },
    i(5, "app-net"),
    t { "", "", "networks:", "  " },
    i(6, "app-net"),
    t { ":", "    driver: bridge", "", "volumes:", "  " },
    i(7, "app-data"),
    t { ":" },
  }),

  s("cmp-start-image", {
    t { "services:", "  " },
    i(1, "app"),
    t { ":", "    image: " },
    i(2, "nginx:alpine"),
    t { "", "    ports:", "      - " },
    i(3, "8080:80"),
    t { "", "    depends_on:", "      - " },
    i(4, "db"),
    t { "", "    env_file:", "      - .env", "    environment:", "      - " },
    i(5, "ENV=dev"),
    t { "", "    restart: unless-stopped", "    networks:", "      - " },
    i(6, "app-net"),
    t { "", "", "networks:", "  " },
    i(7, "app-net"),
    t { ":", "    driver: bridge", "", "volumes:", "  " },
    i(8, "app-data"),
    t { ":" },
  }),

  s("cmp-start", {
    t { "services:", "", "", "", "", "networks:", "  " },
    i(1, "app-net"),
    t { ":", "    driver: bridge", "", "volumes:", "  " },
    i(2, "app-data"),
    t { ":" },
  }),

  s("cmp-serv-image", {
    t { "  " },
    i(1, "app"),
    t { ":", "    image: " },
    i(2, "nginx:alpine"),
    t { "", "    container_name: " },
    i(3, "my-container"),
    t { "", "    ports:", "      - " },
    i(4, "80:80"),
    t { "", "    environment:", "      - " },
    i(5, "KEY=value"),
    t { "", "    env_file:", "      - .env", "    volumes:", "      - " },
    i(6, "./data:/data"),
    t { "", "      - " },
    i(7, "app-data:/var/lib/data"),
    t { "", "    networks:", "      - " },
    i(8, "app-net"),
    t { "", "    depends_on:", "      - " },
    i(9, "db"),
    t { "", "    restart: unless-stopped" },
  }),

  s("cmp-serv-build", {
    t { "  " },
    i(1, "app"),
    t { ":", "    build:", "      context: .", "      dockerfile: Dockerfile", "    container_name: " },
    i(2, "my-container"),
    t { "", "    ports:", "      - " },
    i(3, "8080:8080"),
    t { "", "    environment:", "      - " },
    i(4, "KEY=value"),
    t { "", "    env_file:", "      - .env", "    volumes:", "      - " },
    i(5, "./data:/data"),
    t { "", "      - " },
    i(6, "app-data:/var/lib/data"),
    t { "", "    networks:", "      - " },
    i(7, "app-net"),
    t { "", "    depends_on:", "      - " },
    i(8, "db"),
    t { "", "    restart: unless-stopped" },
  }),

  s("cmp-health", {
    t { "    healthcheck:", '      test: ["CMD", "curl", "-f", "http://localhost:' },
    i(1, "8080"),
    t { '/health"]', "      interval: " },
    i(2, "30s"),
    t { "", "      timeout: " },
    i(3, "10s"),
    t { "", "      retries: " },
    i(4, "3"),
    t { "", "      start_period: " },
    i(5, "40s"),
  }),

  s("cmp-deploy", {
    t { "    deploy:", "      replicas: " },
    i(1, "1"),
    t { "", "      resources:", "        limits:", "          cpus: '" },
    i(2, "1.0"),
    t { "'", "          memory: " },
    i(3, "512M"),
    t { "", "        reservations:", "          cpus: '" },
    i(4, "0.25"),
    t { "'", "          memory: " },
    i(5, "128M"),
    t { "", "      restart_policy:", "        condition: on-failure", "        delay: 5s", "        max_attempts: 3" },
  }),

  s("cmp-vol", {
    t { "  " },
    i(1, "app-data"),
    t { ":", "    driver: local" },
  }),

  s("cmp-net", {
    t { "  " },
    i(1, "app-net"),
    t { ":", "    driver: bridge" },
  }),
}
