local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("prometheus", {
    t { "global:", "" },
    t { "  scrape_interval: " },
    i(1, "60s"),
    t { "", "" },
    t { "  scrape_timeout: " },
    i(2, "10s"),
    t { "", "" },
    t { "  evaluation_interval: " },
    i(3, "15s"),
    t { "", "" },
    t { "" },
    t { "alerting:", "" },
    t { "  alertmanagers:", "" },
    t { "    - scheme: https", "" },
    t { "      tls_config:", "" },
    t { "        ca_file: " },
    i(4, "/etc/prometheus/ca.pem"),
    t { "", "" },
    t { "        cert_file: " },
    i(5, "/etc/prometheus/cert.pem"),
    t { "", "" },
    t { "        key_file: " },
    i(6, "/etc/prometheus/key.pem"),
    t { "", "" },
    t { "      static_configs:", "" },
    t { "        - targets:", "" },
    t { "          - " },
    i(7, "localhost:9093"),
    t { "", "" },
    t { "" },
    t { "rule_files:", "" },
    t { "  - " },
    i(8, "rules/*.yml"),
    t { "", "" },
    t { "" },
    t { "scrape_configs:", "" },
    t { "  - job_name: " },
    i(9, "prometheus"),
    t { "", "" },
    t { "    static_configs:", "" },
    t { "      - targets: [" },
    i(10, "localhost:9090"),
    t { "]", "" },
    t { "" },
    t { "  - job_name: " },
    i(11, "secure-node-exporter"),
    t { "", "" },
    t { "    scheme: https", "" },
    t { "    tls_config:", "" },
    t { "      ca_file: " },
    i(12, "/etc/prometheus/ca.pem"),
    t { "", "" },
    t { "      insecure_skip_verify: " },
    i(13, "false"),
    t { "", "" },
    t { "    static_configs:", "" },
    t { "      - targets: [" },
    i(14, "localhost:9100"),
    t { "]", "" },
  }),
}
